### ISSUE TITLE
2nd Proofreading round Part 4

### ISSUE THREAD

**Issue by e-BaMaMe** [t4d-gmbh/git-and-science#17]
Check for formatting errors, typos, wording, etc.

**Comment by matteodelucchi** [comment]
:wave: @e-BaMaMe , I just merged the results of my rough review in `main` with #20 . Consider incorporating them into your review branch to avoid duplicated work.

**Comment by e-BaMaMe** [comment]
> 👋 @e-BaMaMe , I just merged the results of my rough review in `main` with #20 . Consider incorporating them into your review branch to avoid duplicated work.

Thanks for the heads-up! 😃
